# Streamlit secrets template (rename to secrets.toml and add your real keys)

# Supabase credentials
SUPABASE_URL = "your_supabase_url_here"
SUPABASE_KEY = "your_supabase_anon_key_here"

# These are already in your config.json, but you can override here if needed
# OPENAI_API_KEY = "your_openai_api_key_here"
# FIRECRAWL_API_KEY = "your_firecrawl_api_key_here" 